/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sweyp.app;
import sweyp.structure.Game;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Game game = new Game();
		game.startGame();
    }
}
